#!/usr/bin/env bash
# PreToolUse hook for Bash and Edit|Write (AGENTS.md → Constraints, enforced deterministically).
#   exit 2 + stderr  → the tool call is blocked and Claude sees the reason
#   JSON on stdout    → permissionDecision allow | ask | deny
set -uo pipefail
input="$(cat)"
root="${CLAUDE_PROJECT_DIR:-$PWD}"

field() {
  printf '%s' "$input" | node -e '
    let s = ""
    process.stdin.on("data", (d) => (s += d)).on("end", () => {
      try {
        const j = JSON.parse(s)
        const v = j[process.argv[1]] ?? (j.tool_input || {})[process.argv[1]] ?? ""
        process.stdout.write(typeof v === "string" ? v : JSON.stringify(v))
      } catch {}
    })
  ' "$1"
}
block() { echo "guard: $1" >&2; exit 2; }
decide() {
  node -e '
    console.log(JSON.stringify({ hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: process.argv[1], permissionDecisionReason: "guard: " + process.argv[2] } }))
  ' "$1" "$2"
  exit 0
}
has() { printf '%s' "$1" | grep -qE "$2"; }

tool="$(field tool_name)"

case "$tool" in
  Bash)
    cmd="$(field command)"
    sep='(^|[;&|[:space:]])'
    if has "$cmd" "${sep}(npx |pnpm (exec|dlx) |\./node_modules/\.bin/)?(vitest|playwright)([[:space:]]|$)" &&
      ! has "$cmd" 'dotenv -e \.env\.test|playwright install|pnpm test'; then
      block "run tests through pnpm test:* (they wrap dotenv -e .env.test); bare vitest/playwright can hit the dev database"
    fi
    has "$cmd" 'ALLOW_TESTS_ON_PORT_5432' && block "ALLOW_TESTS_ON_PORT_5432 disables the dev-database guard"
    has "$cmd" "${sep}(npm (i|install|add|ci)|yarn( add| install)?([[:space:]]|$)|npx )" && block "use pnpm (packageManager pin); npm/yarn/npx are not allowed"
    has "$cmd" 'pnpm (run )?db:reset' && block "pnpm db:reset drops the dev database volume; ask the user to run it"
    has "$cmd" 'docker compose down.*(-v|--volumes)' && block "docker compose down -v destroys database volumes"
    has "$cmd" 'git push.*(--force|-f( |$))' && block "force push is not allowed"
    has "$cmd" 'git reset --hard|git checkout -- \.|git clean -f' && block "destructive git command; ask the user"
    if has "$cmd" "${sep}rm -[a-zA-Z]*(rf|fr)" && ! has "$cmd" '/tmp/|\.next|coverage|playwright-report|test-results|node_modules'; then
      block "rm -rf outside build/temp directories; ask the user"
    fi
    if [ "${HARNESS_LOOP:-0}" = "1" ]; then
      # Driver-run session (docs/DECISIONS.md D-008): the driver owns Docker, pushes and worktrees.
      has "$cmd" "${sep}pnpm (run )?db:(up|down)|${sep}docker compose (up|down|stop|rm)" && block "Docker services are managed by the loop driver; they are already running"
      has "$cmd" "${sep}git push" && block "the loop driver pushes the branch and opens the PR; commit only"
      has "$cmd" "${sep}git (checkout|switch) (main|master)|${sep}git worktree (add|remove|prune)" && block "stay on this feature branch; the loop driver manages worktrees"
    fi
    if has "$cmd" "${sep}git commit"; then
      out="$(cd "$root" && pnpm --silent harness:check 2>&1)" || block "feature_list.json is invalid; fix it before committing: ${out}"
    fi
    ;;
  Edit|Write|MultiEdit)
    file="$(field file_path)"
    rel="${file#"$root"/}"
    case "$rel" in
      src/payload-types.ts) decide deny "generated by pnpm generate:types; never hand-edit" ;;
      "src/app/(payload)/admin/importMap.js") decide deny "generated by pnpm generate:importmap; never hand-edit" ;;
      pnpm-lock.yaml) decide deny "the lockfile is managed by pnpm install" ;;
      .env | .env.local | .env.*.local) decide deny "secrets; document variables in .env.example instead" ;;
      "src/app/(payload)/admin/"* | "src/app/(payload)/api/"*) decide ask "generated Payload route (src/ARCHITECTURE.md); confirm this file is meant to be hand-edited" ;;
      src/payload/migrations/index.ts) ;;
      src/payload/migrations/*) decide ask "migrations come from pnpm db:migrate:create; hand edits only for PostGIS SQL (docs/DECISIONS.md D-003)" ;;
      AGENTS.md)
        if [ "$tool" = "Write" ]; then
          decide ask "rewriting AGENTS.md: keep the nextjs-agent-rules marker block intact (next dev regenerates it)"
        fi
        if has "$(field old_string)$(field new_string)" 'nextjs-agent-rules|This is NOT the Next.js you know'; then
          decide ask "this edit touches the Next.js marker block in AGENTS.md, which next dev regenerates"
        fi
        ;;
    esac
    ;;
esac
exit 0
