import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * MV-032: `watch_areas` per `01 §3.2` (ledger D4). Generated by `payload migrate:create`
 * and hand-edited so that `notify_by_email` is renamed (data kept) instead of dropped and
 * re-added; the GIST index statement is a no-op guard (the initial migration creates it,
 * ticket: "add the GIST index if missing"). Radii above the new 5 000 m maximum are
 * clamped so existing rows stay editable under the collection's `max` validation.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "watch_areas" RENAME COLUMN "notify_by_email" TO "notifications_enabled";
  ALTER TABLE "watch_areas" ADD COLUMN IF NOT EXISTS "address_label" varchar;
  ALTER TABLE "watch_areas" ADD COLUMN IF NOT EXISTS "last_checked_at" timestamp(3) with time zone;
  ALTER TABLE "watch_areas" ADD COLUMN IF NOT EXISTS "last_declaration_count" numeric;
  UPDATE "watch_areas" SET "radius_m" = 5000 WHERE "radius_m" > 5000;
  CREATE INDEX IF NOT EXISTS "watch_areas_geom_3067_gist" ON "watch_areas" USING gist ("geom_3067");`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "watch_areas" DROP COLUMN IF EXISTS "last_declaration_count";
  ALTER TABLE "watch_areas" DROP COLUMN IF EXISTS "last_checked_at";
  ALTER TABLE "watch_areas" DROP COLUMN IF EXISTS "address_label";
  ALTER TABLE "watch_areas" RENAME COLUMN "notifications_enabled" TO "notify_by_email";`)
}
