import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * MV-033: `declarations` per `01 §3.3` (ledger D6) and the new `declaration_revisions`
 * table. Generated by `payload migrate:create` as two diffs (add, then drop; see the
 * README's rename recipe) and merged by hand so the scaffold columns are renamed (data
 * kept) instead of dropped and re-added: `metsakeskus_id` → `source_id`, `hakkuutapa` →
 * `cutting_type_code`, `arrival_date` → `received_at`, `properties` → `raw_attributes`,
 * `first_seen` → `first_seen_at`, `last_seen` → `last_seen_at`; `updated_at_source` is
 * dropped. `attr_hash` is NOT NULL: existing rows get the sentinel `''`, which differs
 * from every real hash, so the next `fetch-declarations` run rewrites them (and fills
 * `cutting_type_label`). `centroid` is a generated PostGIS column (`ST_Centroid(geom)`),
 * like `watch_areas.geom_3067` (D-003); the GIST index on `geom` is a no-op guard.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TABLE IF NOT EXISTS "declaration_revisions" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"declaration_id" integer NOT NULL,
  	"prev_geom_hash" varchar NOT NULL,
  	"prev_attr_hash" varchar NOT NULL,
  	"prev_raw_attributes" jsonb,
  	"changed_at" timestamp(3) with time zone NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );

  ALTER TABLE "declarations" RENAME COLUMN "metsakeskus_id" TO "source_id";
  ALTER TABLE "declarations" RENAME COLUMN "hakkuutapa" TO "cutting_type_code";
  ALTER TABLE "declarations" RENAME COLUMN "arrival_date" TO "received_at";
  ALTER TABLE "declarations" RENAME COLUMN "properties" TO "raw_attributes";
  ALTER TABLE "declarations" RENAME COLUMN "first_seen" TO "first_seen_at";
  ALTER TABLE "declarations" RENAME COLUMN "last_seen" TO "last_seen_at";
  ALTER INDEX "declarations_metsakeskus_id_idx" RENAME TO "declarations_source_id_idx";
  ALTER INDEX "declarations_last_seen_idx" RENAME TO "declarations_last_seen_at_idx";
  ALTER TABLE "declarations" DROP COLUMN IF EXISTS "updated_at_source";

  ALTER TABLE "declarations" ADD COLUMN IF NOT EXISTS "source_layer_version" varchar;
  ALTER TABLE "declarations" ADD COLUMN IF NOT EXISTS "cutting_type_label" varchar;
  ALTER TABLE "declarations" ADD COLUMN IF NOT EXISTS "valid_until" timestamp(3) with time zone;
  ALTER TABLE "declarations" ADD COLUMN IF NOT EXISTS "municipality_code" varchar;
  ALTER TABLE "declarations" ADD COLUMN IF NOT EXISTS "attr_hash" varchar DEFAULT '' NOT NULL;
  ALTER TABLE "declarations" ALTER COLUMN "attr_hash" DROP DEFAULT;
  ALTER TABLE "declarations" ADD COLUMN IF NOT EXISTS "removed_at" timestamp(3) with time zone;
  UPDATE "declarations" SET "valid_until" = "received_at" + interval '3 years' WHERE "valid_until" IS NULL AND "received_at" IS NOT NULL;
  ALTER TABLE "declarations" ADD COLUMN IF NOT EXISTS "centroid" geometry(Point,3067) GENERATED ALWAYS AS (ST_Centroid("geom")) STORED;

  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN IF NOT EXISTS "declaration_revisions_id" integer;
  ALTER TABLE "declaration_revisions" ADD CONSTRAINT "declaration_revisions_declaration_id_declarations_id_fk" FOREIGN KEY ("declaration_id") REFERENCES "public"."declarations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_declaration_revisions_fk" FOREIGN KEY ("declaration_revisions_id") REFERENCES "public"."declaration_revisions"("id") ON DELETE cascade ON UPDATE no action;

  CREATE INDEX IF NOT EXISTS "declaration_revisions_declaration_idx" ON "declaration_revisions" USING btree ("declaration_id");
  CREATE INDEX IF NOT EXISTS "declaration_revisions_changed_at_idx" ON "declaration_revisions" USING btree ("changed_at");
  CREATE INDEX IF NOT EXISTS "declaration_revisions_updated_at_idx" ON "declaration_revisions" USING btree ("updated_at");
  CREATE INDEX IF NOT EXISTS "declaration_revisions_created_at_idx" ON "declaration_revisions" USING btree ("created_at");
  CREATE INDEX IF NOT EXISTS "declarations_valid_until_idx" ON "declarations" USING btree ("valid_until");
  CREATE INDEX IF NOT EXISTS "declarations_attr_hash_idx" ON "declarations" USING btree ("attr_hash");
  CREATE INDEX IF NOT EXISTS "declarations_removed_at_idx" ON "declarations" USING btree ("removed_at");
  CREATE INDEX IF NOT EXISTS "declarations_geom_gist" ON "declarations" USING gist ("geom");
  CREATE INDEX IF NOT EXISTS "declarations_centroid_gist" ON "declarations" USING gist ("centroid");
  CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_declaration_revisions_id_idx" ON "payload_locked_documents_rels" USING btree ("declaration_revisions_id");`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_declaration_revisions_fk";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_declaration_revisions_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN IF EXISTS "declaration_revisions_id";
  DROP TABLE IF EXISTS "declaration_revisions" CASCADE;

  DROP INDEX IF EXISTS "declarations_centroid_gist";
  DROP INDEX IF EXISTS "declarations_removed_at_idx";
  DROP INDEX IF EXISTS "declarations_attr_hash_idx";
  DROP INDEX IF EXISTS "declarations_valid_until_idx";
  ALTER TABLE "declarations" DROP COLUMN IF EXISTS "centroid";
  ALTER TABLE "declarations" DROP COLUMN IF EXISTS "removed_at";
  ALTER TABLE "declarations" DROP COLUMN IF EXISTS "attr_hash";
  ALTER TABLE "declarations" DROP COLUMN IF EXISTS "municipality_code";
  ALTER TABLE "declarations" DROP COLUMN IF EXISTS "valid_until";
  ALTER TABLE "declarations" DROP COLUMN IF EXISTS "cutting_type_label";
  ALTER TABLE "declarations" DROP COLUMN IF EXISTS "source_layer_version";

  ALTER TABLE "declarations" ADD COLUMN IF NOT EXISTS "updated_at_source" timestamp(3) with time zone;
  ALTER INDEX "declarations_last_seen_at_idx" RENAME TO "declarations_last_seen_idx";
  ALTER INDEX "declarations_source_id_idx" RENAME TO "declarations_metsakeskus_id_idx";
  ALTER TABLE "declarations" RENAME COLUMN "last_seen_at" TO "last_seen";
  ALTER TABLE "declarations" RENAME COLUMN "first_seen_at" TO "first_seen";
  ALTER TABLE "declarations" RENAME COLUMN "raw_attributes" TO "properties";
  ALTER TABLE "declarations" RENAME COLUMN "received_at" TO "arrival_date";
  ALTER TABLE "declarations" RENAME COLUMN "cutting_type_code" TO "hakkuutapa";
  ALTER TABLE "declarations" RENAME COLUMN "source_id" TO "metsakeskus_id";`)
}
