import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * MV-034: `watch_area_declarations` (`01 §3.4`) and `alerts` per `01 §3.5` (ledger D2, D5,
 * D7). Generated by `payload migrate:create` as two diffs (add the new table and columns,
 * then drop the old alert columns; see the README's rename recipe) and merged by hand so
 * existing alerts are converted instead of lost: `kind` → `change_type` (`changed` becomes
 * `geometry_changed`), `status = 'sent'` + `sent_at` → `notified_at`, `snapshot` is built
 * from the current declaration row, and the join table is seeded from the latest alert per
 * (watch_area, declaration) so the next `match-watch-areas` run stays idempotent (its
 * `geom_hash` moved to `last_seen_geom_hash`). Hand edits beyond the merge: the join-table
 * foreign keys cascade (a row is meaningless without either side and the columns are NOT
 * NULL, so Payload's `set null` would block deleting a watch area) and `(user, created_at)`
 * is DESC as the spec asks. Index names are the ones Payload derives for compound indexes
 * (no table prefix) so the schema snapshot and the database agree.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   DO $$ BEGIN
    CREATE TYPE "public"."enum_alerts_change_type" AS ENUM('new', 'geometry_changed', 'attributes_changed', 'removed');
  EXCEPTION WHEN duplicate_object THEN NULL; END $$;

  CREATE TABLE IF NOT EXISTS "watch_area_declarations" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"watch_area_id" integer NOT NULL,
  	"declaration_id" integer NOT NULL,
  	"first_matched_at" timestamp(3) with time zone NOT NULL,
  	"last_matched_at" timestamp(3) with time zone NOT NULL,
  	"last_seen_geom_hash" varchar NOT NULL,
  	"last_seen_attr_hash" varchar NOT NULL,
  	"distance_m" numeric NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  ALTER TABLE "watch_area_declarations" DROP CONSTRAINT IF EXISTS "watch_area_declarations_watch_area_id_watch_areas_id_fk";
  ALTER TABLE "watch_area_declarations" DROP CONSTRAINT IF EXISTS "watch_area_declarations_declaration_id_declarations_id_fk";
  ALTER TABLE "watch_area_declarations" ADD CONSTRAINT "watch_area_declarations_watch_area_id_watch_areas_id_fk" FOREIGN KEY ("watch_area_id") REFERENCES "public"."watch_areas"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "watch_area_declarations" ADD CONSTRAINT "watch_area_declarations_declaration_id_declarations_id_fk" FOREIGN KEY ("declaration_id") REFERENCES "public"."declarations"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX IF NOT EXISTS "watch_area_declarations_watch_area_idx" ON "watch_area_declarations" USING btree ("watch_area_id");
  CREATE INDEX IF NOT EXISTS "watch_area_declarations_declaration_idx" ON "watch_area_declarations" USING btree ("declaration_id");
  CREATE INDEX IF NOT EXISTS "watch_area_declarations_updated_at_idx" ON "watch_area_declarations" USING btree ("updated_at");
  CREATE INDEX IF NOT EXISTS "watch_area_declarations_created_at_idx" ON "watch_area_declarations" USING btree ("created_at");
  CREATE UNIQUE INDEX IF NOT EXISTS "watchArea_declaration_idx" ON "watch_area_declarations" USING btree ("watch_area_id","declaration_id");

  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN IF NOT EXISTS "watch_area_declarations_id" integer;
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_watch_area_declarations_fk";
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_watch_area_declarations_fk" FOREIGN KEY ("watch_area_declarations_id") REFERENCES "public"."watch_area_declarations"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_watch_area_declarations_id_idx" ON "payload_locked_documents_rels" USING btree ("watch_area_declarations_id");

  ALTER TABLE "alerts" ADD COLUMN IF NOT EXISTS "change_type" "enum_alerts_change_type";
  ALTER TABLE "alerts" ADD COLUMN IF NOT EXISTS "notified_at" timestamp(3) with time zone;
  ALTER TABLE "alerts" ADD COLUMN IF NOT EXISTS "snapshot" jsonb;
  ALTER TABLE "alerts" ADD COLUMN IF NOT EXISTS "read_at" timestamp(3) with time zone;

  UPDATE "alerts" SET "change_type" = CASE WHEN "kind" = 'changed' THEN 'geometry_changed' ELSE 'new' END::"enum_alerts_change_type" WHERE "change_type" IS NULL;
  UPDATE "alerts" SET "notified_at" = "sent_at" WHERE "notified_at" IS NULL AND "status" = 'sent';
  UPDATE "alerts" a SET "snapshot" = jsonb_build_object(
      'cuttingTypeLabel', d."cutting_type_label",
      'areaHa', d."area_ha",
      'distanceM', COALESCE(a."distance_m", 0),
      'receivedAt', d."received_at")
    FROM "declarations" d WHERE d."id" = a."declaration_id" AND a."snapshot" IS NULL;
  UPDATE "alerts" SET "snapshot" = jsonb_build_object('distanceM', COALESCE("distance_m", 0)) WHERE "snapshot" IS NULL;

  INSERT INTO "watch_area_declarations" ("watch_area_id", "declaration_id", "first_matched_at", "last_matched_at", "last_seen_geom_hash", "last_seen_attr_hash", "distance_m")
    SELECT a."watch_area_id", a."declaration_id", MIN(a."created_at"), MAX(a."created_at"),
           (array_agg(a."geom_hash" ORDER BY a."created_at" DESC))[1], d."attr_hash",
           COALESCE((array_agg(a."distance_m" ORDER BY a."created_at" DESC))[1], 0)
    FROM "alerts" a JOIN "declarations" d ON d."id" = a."declaration_id"
    GROUP BY a."watch_area_id", a."declaration_id", d."attr_hash"
    ON CONFLICT ("watch_area_id", "declaration_id") DO NOTHING;

  ALTER TABLE "alerts" ALTER COLUMN "change_type" SET NOT NULL;
  ALTER TABLE "alerts" ALTER COLUMN "snapshot" SET NOT NULL;
  CREATE INDEX IF NOT EXISTS "user_createdAt_idx" ON "alerts" USING btree ("user_id","created_at" DESC);
  CREATE INDEX IF NOT EXISTS "user_notifiedAt_idx" ON "alerts" USING btree ("user_id","notified_at");

  DROP INDEX IF EXISTS "alerts_geom_hash_idx";
  DROP INDEX IF EXISTS "alerts_status_idx";
  ALTER TABLE "alerts" DROP COLUMN IF EXISTS "kind";
  ALTER TABLE "alerts" DROP COLUMN IF EXISTS "distance_m";
  ALTER TABLE "alerts" DROP COLUMN IF EXISTS "geom_hash";
  ALTER TABLE "alerts" DROP COLUMN IF EXISTS "status";
  ALTER TABLE "alerts" DROP COLUMN IF EXISTS "sent_at";
  DROP TYPE IF EXISTS "public"."enum_alerts_kind";
  DROP TYPE IF EXISTS "public"."enum_alerts_status";`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DO $$ BEGIN
    CREATE TYPE "public"."enum_alerts_kind" AS ENUM('new', 'changed');
  EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  DO $$ BEGIN
    CREATE TYPE "public"."enum_alerts_status" AS ENUM('pending', 'sent', 'failed');
  EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  ALTER TABLE "alerts" ADD COLUMN IF NOT EXISTS "kind" "enum_alerts_kind";
  ALTER TABLE "alerts" ADD COLUMN IF NOT EXISTS "distance_m" numeric;
  ALTER TABLE "alerts" ADD COLUMN IF NOT EXISTS "geom_hash" varchar;
  ALTER TABLE "alerts" ADD COLUMN IF NOT EXISTS "status" "enum_alerts_status" DEFAULT 'pending' NOT NULL;
  ALTER TABLE "alerts" ADD COLUMN IF NOT EXISTS "sent_at" timestamp(3) with time zone;

  UPDATE "alerts" SET "kind" = CASE WHEN "change_type" = 'new' THEN 'new' ELSE 'changed' END::"enum_alerts_kind" WHERE "kind" IS NULL;
  UPDATE "alerts" SET "status" = 'sent', "sent_at" = "notified_at" WHERE "notified_at" IS NOT NULL;
  UPDATE "alerts" SET "distance_m" = ("snapshot"->>'distanceM')::numeric WHERE "distance_m" IS NULL AND jsonb_typeof("snapshot"->'distanceM') = 'number';
  UPDATE "alerts" a SET "geom_hash" = w."last_seen_geom_hash" FROM "watch_area_declarations" w
    WHERE w."watch_area_id" = a."watch_area_id" AND w."declaration_id" = a."declaration_id" AND a."geom_hash" IS NULL;
  UPDATE "alerts" SET "geom_hash" = '' WHERE "geom_hash" IS NULL;
  ALTER TABLE "alerts" ALTER COLUMN "kind" SET NOT NULL;
  ALTER TABLE "alerts" ALTER COLUMN "geom_hash" SET NOT NULL;
  CREATE INDEX IF NOT EXISTS "alerts_geom_hash_idx" ON "alerts" USING btree ("geom_hash");
  CREATE INDEX IF NOT EXISTS "alerts_status_idx" ON "alerts" USING btree ("status");

  DROP INDEX IF EXISTS "user_createdAt_idx";
  DROP INDEX IF EXISTS "user_notifiedAt_idx";
  ALTER TABLE "alerts" DROP COLUMN IF EXISTS "change_type";
  ALTER TABLE "alerts" DROP COLUMN IF EXISTS "notified_at";
  ALTER TABLE "alerts" DROP COLUMN IF EXISTS "snapshot";
  ALTER TABLE "alerts" DROP COLUMN IF EXISTS "read_at";
  DROP TYPE IF EXISTS "public"."enum_alerts_change_type";

  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_watch_area_declarations_fk";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_watch_area_declarations_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN IF EXISTS "watch_area_declarations_id";
  DROP TABLE IF EXISTS "watch_area_declarations" CASCADE;`)
}
