/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'watch-areas': WatchArea;
    declarations: Declaration;
    'declaration-revisions': DeclarationRevision;
    'watch-area-declarations': WatchAreaDeclaration;
    alerts: Alert;
    'notification-log': NotificationLog;
    'consent-events': ConsentEvent;
    'data-export-requests': DataExportRequest;
    exports: Export;
    'job-runs': JobRun;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'watch-areas': WatchAreasSelect<false> | WatchAreasSelect<true>;
    declarations: DeclarationsSelect<false> | DeclarationsSelect<true>;
    'declaration-revisions': DeclarationRevisionsSelect<false> | DeclarationRevisionsSelect<true>;
    'watch-area-declarations': WatchAreaDeclarationsSelect<false> | WatchAreaDeclarationsSelect<true>;
    alerts: AlertsSelect<false> | AlertsSelect<true>;
    'notification-log': NotificationLogSelect<false> | NotificationLogSelect<true>;
    'consent-events': ConsentEventsSelect<false> | ConsentEventsSelect<true>;
    'data-export-requests': DataExportRequestsSelect<false> | DataExportRequestsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    'job-runs': JobRunsSelect<false> | JobRunsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'fetch-declarations': TaskFetchDeclarations;
      'match-watch-areas': TaskMatchWatchAreas;
      'send-alerts': TaskSendAlerts;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      'sync-declarations': WorkflowSyncDeclarations;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'user' | 'admin';
  locale?: ('fi' | 'en') | null;
  timezone?: string | null;
  marketingConsent?: boolean | null;
  /**
   * Asetetaan automaattisesti, kun lupa annetaan.
   */
  marketingConsentAt?: string | null;
  notificationPrefs?: {
    enabled?: boolean | null;
    mode?: ('immediate' | 'daily' | 'weekly') | null;
    /**
     * Tunti (0–23) käyttäjän aikavyöhykkeellä.
     */
    dailyHour?: number | null;
  };
  plan?: 'free' | null;
  /**
   * Poistotyön merkki; rivi poistetaan pysyvästi työn lopussa.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-areas".
 */
export interface WatchArea {
  id: number;
  name: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  center: [number, number];
  /**
   * 100–5000 m.
   */
  radiusM: number;
  owner: number | User;
  notificationsEnabled?: boolean | null;
  /**
   * Geokoodattu osoite tai paikannimi keskipisteelle.
   */
  addressLabel?: string | null;
  lastCheckedAt?: string | null;
  lastDeclarationCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "declarations".
 */
export interface Declaration {
  id: number;
  sourceId: string;
  sourceLayerVersion?: string | null;
  declarationNumber: string;
  cuttingTypeCode?: number | null;
  /**
   * Johdettu koodista (lib/wfs/hakkuutapa.ts).
   */
  cuttingTypeLabel?: string | null;
  areaHa?: number | null;
  receivedAt?: string | null;
  /**
   * Saapumispäivä + 3 vuotta.
   */
  validUntil?: string | null;
  municipalityCode?: string | null;
  rawAttributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  geomHash: string;
  attrHash: string;
  firstSeenAt: string;
  lastSeenAt: string;
  /**
   * Asetetaan, kun kohde puuttuu tuloksista kolmella peräkkäisellä ajolla.
   */
  removedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "declaration-revisions".
 */
export interface DeclarationRevision {
  id: number;
  declaration: number | Declaration;
  prevGeomHash: string;
  prevAttrHash: string;
  prevRawAttributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  changedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-area-declarations".
 */
export interface WatchAreaDeclaration {
  id: number;
  watchArea: number | WatchArea;
  declaration: number | Declaration;
  firstMatchedAt: string;
  lastMatchedAt: string;
  /**
   * Geometrian tiiviste viimeisellä osumalla.
   */
  lastSeenGeomHash: string;
  /**
   * Attribuuttien tiiviste viimeisellä osumalla.
   */
  lastSeenAttrHash: string;
  /**
   * 0, kun keskipiste on kuvion sisällä.
   */
  distanceM: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts".
 */
export interface Alert {
  id: number;
  user: number | User;
  watchArea: number | WatchArea;
  declaration: number | Declaration;
  changeType: 'new' | 'geometry_changed' | 'attributes_changed' | 'removed';
  /**
   * Sähköposti lähetetty.
   */
  notifiedAt?: string | null;
  /**
   * cuttingTypeLabel, areaHa, distanceM, receivedAt hälytyshetkellä (syöte ei muutu, vaikka ilmoitus muuttuisi).
   */
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-log".
 */
export interface NotificationLog {
  id: number;
  user?: (number | null) | User;
  type:
    | 'alert_immediate'
    | 'alert_digest'
    | 'verify_email'
    | 'password_reset'
    | 'email_change'
    | 'data_export'
    | 'account_deleted';
  alerts?: (number | Alert)[] | null;
  recipient?: string | null;
  provider: string;
  providerMessageId?: string | null;
  status: 'queued' | 'sent' | 'failed';
  error?: string | null;
  sentAt?: string | null;
  jobRunId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-events".
 */
export interface ConsentEvent {
  id: number;
  user?: (number | null) | User;
  kind: 'terms' | 'privacy' | 'marketing' | 'cookies';
  version: string;
  granted: boolean;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-export-requests".
 */
export interface DataExportRequest {
  id: number;
  user: number | User;
  status: 'pending' | 'ready' | 'expired' | 'failed';
  file?: (number | null) | Export;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  user: number | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-runs".
 */
export interface JobRun {
  id: number;
  task: 'fetch-declarations' | 'match-watch-areas' | 'send-alerts' | 'cleanup' | 'export' | 'delete-account';
  startedAt: string;
  finishedAt?: string | null;
  status: 'running' | 'succeeded' | 'failed';
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'fetch-declarations' | 'match-watch-areas' | 'send-alerts';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'sync-declarations' | null;
  taskSlug?: ('inline' | 'fetch-declarations' | 'match-watch-areas' | 'send-alerts') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'watch-areas';
        value: number | WatchArea;
      } | null)
    | ({
        relationTo: 'declarations';
        value: number | Declaration;
      } | null)
    | ({
        relationTo: 'declaration-revisions';
        value: number | DeclarationRevision;
      } | null)
    | ({
        relationTo: 'watch-area-declarations';
        value: number | WatchAreaDeclaration;
      } | null)
    | ({
        relationTo: 'alerts';
        value: number | Alert;
      } | null)
    | ({
        relationTo: 'notification-log';
        value: number | NotificationLog;
      } | null)
    | ({
        relationTo: 'consent-events';
        value: number | ConsentEvent;
      } | null)
    | ({
        relationTo: 'data-export-requests';
        value: number | DataExportRequest;
      } | null)
    | ({
        relationTo: 'exports';
        value: number | Export;
      } | null)
    | ({
        relationTo: 'job-runs';
        value: number | JobRun;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  locale?: T;
  timezone?: T;
  marketingConsent?: T;
  marketingConsentAt?: T;
  notificationPrefs?:
    | T
    | {
        enabled?: T;
        mode?: T;
        dailyHour?: T;
      };
  plan?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-areas_select".
 */
export interface WatchAreasSelect<T extends boolean = true> {
  name?: T;
  center?: T;
  radiusM?: T;
  owner?: T;
  notificationsEnabled?: T;
  addressLabel?: T;
  lastCheckedAt?: T;
  lastDeclarationCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "declarations_select".
 */
export interface DeclarationsSelect<T extends boolean = true> {
  sourceId?: T;
  sourceLayerVersion?: T;
  declarationNumber?: T;
  cuttingTypeCode?: T;
  cuttingTypeLabel?: T;
  areaHa?: T;
  receivedAt?: T;
  validUntil?: T;
  municipalityCode?: T;
  rawAttributes?: T;
  geomHash?: T;
  attrHash?: T;
  firstSeenAt?: T;
  lastSeenAt?: T;
  removedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "declaration-revisions_select".
 */
export interface DeclarationRevisionsSelect<T extends boolean = true> {
  declaration?: T;
  prevGeomHash?: T;
  prevAttrHash?: T;
  prevRawAttributes?: T;
  changedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-area-declarations_select".
 */
export interface WatchAreaDeclarationsSelect<T extends boolean = true> {
  watchArea?: T;
  declaration?: T;
  firstMatchedAt?: T;
  lastMatchedAt?: T;
  lastSeenGeomHash?: T;
  lastSeenAttrHash?: T;
  distanceM?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts_select".
 */
export interface AlertsSelect<T extends boolean = true> {
  user?: T;
  watchArea?: T;
  declaration?: T;
  changeType?: T;
  notifiedAt?: T;
  snapshot?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-log_select".
 */
export interface NotificationLogSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  alerts?: T;
  recipient?: T;
  provider?: T;
  providerMessageId?: T;
  status?: T;
  error?: T;
  sentAt?: T;
  jobRunId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-events_select".
 */
export interface ConsentEventsSelect<T extends boolean = true> {
  user?: T;
  kind?: T;
  version?: T;
  granted?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-export-requests_select".
 */
export interface DataExportRequestsSelect<T extends boolean = true> {
  user?: T;
  status?: T;
  file?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  user?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-runs_select".
 */
export interface JobRunsSelect<T extends boolean = true> {
  task?: T;
  startedAt?: T;
  finishedAt?: T;
  status?: T;
  stats?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFetch-declarations".
 */
export interface TaskFetchDeclarations {
  input?: unknown;
  output: {
    watchAreas: number;
    fetched: number;
    created: number;
    updated: number;
    revisions: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskMatch-watch-areas".
 */
export interface TaskMatchWatchAreas {
  input?: unknown;
  output: {
    matched: number;
    alertsCreated: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-alerts".
 */
export interface TaskSendAlerts {
  input?: unknown;
  output: {
    emailsSent: number;
    emailsFailed: number;
    alertsHandled: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowSync-declarations".
 */
export interface WorkflowSyncDeclarations {
  input?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}